Warning: no access to tty (Bad file descriptor).
Thus no job control in this shell.
/var/spool/PBS/mom_priv/jobs/175654.hpcc-con.SC: line 7: module: command not found
/var/spool/PBS/mom_priv/jobs/175654.hpcc-con.SC: line 8: conda: command not found
/var/spool/PBS/mom_priv/jobs/175654.hpcc-con.SC: line 9: activate: No such file or directory
Collecting appnope==0.1.0 (from -r /home/s1510756/hpcc/requirements.txt (line 1))
  Using cached appnope-0.1.0-py2.py3-none-any.whl
Collecting backports-abc==0.4 (from -r /home/s1510756/hpcc/requirements.txt (line 2))
  Using cached backports_abc-0.4-py2.py3-none-any.whl
Collecting backports.ssl-match-hostname==3.4.0.2 (from -r /home/s1510756/hpcc/requirements.txt (line 3))
  Using cached backports.ssl_match_hostname-3.4.0.2.tar.gz
Collecting cffi==1.8.3 (from -r /home/s1510756/hpcc/requirements.txt (line 4))
  Using cached cffi-1.8.3-cp27-cp27mu-manylinux1_x86_64.whl
Collecting cycler==0.10.0 (from -r /home/s1510756/hpcc/requirements.txt (line 5))
  Using cached cycler-0.10.0-py2.py3-none-any.whl
Collecting decorator==4.0.9 (from -r /home/s1510756/hpcc/requirements.txt (line 6))
  Using cached decorator-4.0.9-py2.py3-none-any.whl
Collecting enum34==1.1.2 (from -r /home/s1510756/hpcc/requirements.txt (line 7))
  Using cached enum34-1.1.2.tar.gz
Collecting gensim==0.12.2 (from -r /home/s1510756/hpcc/requirements.txt (line 8))
  Using cached gensim-0.12.2.tar.gz
Collecting ipykernel==4.3.1 (from -r /home/s1510756/hpcc/requirements.txt (line 9))
  Using cached ipykernel-4.3.1-py2.py3-none-any.whl
Collecting ipython==4.1.2 (from -r /home/s1510756/hpcc/requirements.txt (line 10))
  Using cached ipython-4.1.2-py2-none-any.whl
Collecting ipython-genutils==0.1.0 (from -r /home/s1510756/hpcc/requirements.txt (line 11))
  Using cached ipython_genutils-0.1.0-py2.py3-none-any.whl
Collecting ipywidgets==4.1.1 (from -r /home/s1510756/hpcc/requirements.txt (line 12))
  Using cached ipywidgets-4.1.1-py2.py3-none-any.whl
Collecting Jinja2==2.8 (from -r /home/s1510756/hpcc/requirements.txt (line 13))
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting jsonschema==2.4.0 (from -r /home/s1510756/hpcc/requirements.txt (line 14))
  Using cached jsonschema-2.4.0-py2.py3-none-any.whl
Collecting jupyter==1.0.0 (from -r /home/s1510756/hpcc/requirements.txt (line 15))
  Using cached jupyter-1.0.0-py2.py3-none-any.whl
Collecting jupyter-client==4.2.2 (from -r /home/s1510756/hpcc/requirements.txt (line 16))
  Using cached jupyter_client-4.2.2-py2.py3-none-any.whl
Collecting jupyter-console==4.1.1 (from -r /home/s1510756/hpcc/requirements.txt (line 17))
  Using cached jupyter_console-4.1.1-py2.py3-none-any.whl
Collecting jupyter-core==4.1.0 (from -r /home/s1510756/hpcc/requirements.txt (line 18))
  Using cached jupyter_core-4.1.0-py2.py3-none-any.whl
Collecting MarkupSafe==0.23 (from -r /home/s1510756/hpcc/requirements.txt (line 19))
  Using cached MarkupSafe-0.23.tar.gz
Collecting matplotlib==1.5.1 (from -r /home/s1510756/hpcc/requirements.txt (line 20))
  Using cached matplotlib-1.5.1.tar.gz
Collecting mistune==0.7.2 (from -r /home/s1510756/hpcc/requirements.txt (line 21))
  Using cached mistune-0.7.2-py2.py3-none-any.whl
Collecting nbconvert==4.1.0 (from -r /home/s1510756/hpcc/requirements.txt (line 22))
  Using cached nbconvert-4.1.0-py2.py3-none-any.whl
Collecting nbformat==4.0.1 (from -r /home/s1510756/hpcc/requirements.txt (line 23))
  Using cached nbformat-4.0.1-py2.py3-none-any.whl
Collecting notebook==4.1.0 (from -r /home/s1510756/hpcc/requirements.txt (line 24))
  Using cached notebook-4.1.0-py2.py3-none-any.whl
Collecting numpy==1.10.4 (from -r /home/s1510756/hpcc/requirements.txt (line 25))
  Using cached numpy-1.10.4-cp27-cp27mu-manylinux1_x86_64.whl
Collecting pexpect==4.0.1 (from -r /home/s1510756/hpcc/requirements.txt (line 26))
  Using cached pexpect-4.0.1.tar.gz
Collecting pickleshare==0.5 (from -r /home/s1510756/hpcc/requirements.txt (line 27))
  Using cached pickleshare-0.5.tar.gz
Collecting psutil==4.1.0 (from -r /home/s1510756/hpcc/requirements.txt (line 28))
  Using cached psutil-4.1.0.tar.gz
Collecting psycopg2==2.6.1 (from -r /home/s1510756/hpcc/requirements.txt (line 29))
  Using cached psycopg2-2.6.1.tar.gz
Collecting ptyprocess==0.5 (from -r /home/s1510756/hpcc/requirements.txt (line 30))
  Using cached ptyprocess-0.5.tar.gz
Collecting pycparser==2.14 (from -r /home/s1510756/hpcc/requirements.txt (line 31))
  Using cached pycparser-2.14.tar.gz
Collecting pygit2==0.24.1 (from -r /home/s1510756/hpcc/requirements.txt (line 32))
  Using cached pygit2-0.24.1.tar.gz
    Complete output from command python setup.py egg_info:
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    c/_cffi_backend.c:15:17: error: ffi.h: No such file or directory
    In file included from c/_cffi_backend.c:63:
    c/malloc_closure.h:81: error: expected specifier-qualifier-list before ‘ffi_closure’
    c/malloc_closure.h: In function ‘more_core’:
    c/malloc_closure.h:117: warning: division by zero
    c/malloc_closure.h:149: error: ‘union mmaped_block’ has no member named ‘next’
    c/malloc_closure.h: At top level:
    c/malloc_closure.h:158: error: expected ‘)’ before ‘*’ token
    c/malloc_closure.h:166: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
    c/_cffi_backend.c:258: error: expected specifier-qualifier-list before ‘ffi_cif’
    c/_cffi_backend.c: In function ‘cdataowninggc_dealloc’:
    c/_cffi_backend.c:1643: error: ‘ffi_closure’ undeclared (first use in this function)
    c/_cffi_backend.c:1643: error: (Each undeclared identifier is reported only once
    c/_cffi_backend.c:1643: error: for each function it appears in.)
    c/_cffi_backend.c:1643: error: ‘closure’ undeclared (first use in this function)
    c/_cffi_backend.c:1643: error: expected expression before ‘)’ token
    c/_cffi_backend.c:1646: warning: implicit declaration of function ‘cffi_closure_free’
    c/_cffi_backend.c: In function ‘cdataowninggc_traverse’:
    c/_cffi_backend.c:1663: error: ‘ffi_closure’ undeclared (first use in this function)
    c/_cffi_backend.c:1663: error: ‘closure’ undeclared (first use in this function)
    c/_cffi_backend.c:1663: error: expected expression before ‘)’ token
    c/_cffi_backend.c: In function ‘cdataowninggc_clear’:
    c/_cffi_backend.c:1684: error: ‘ffi_closure’ undeclared (first use in this function)
    c/_cffi_backend.c:1684: error: ‘closure’ undeclared (first use in this function)
    c/_cffi_backend.c:1684: error: expected expression before ‘)’ token
    c/_cffi_backend.c: In function ‘cdataowninggc_repr’:
    c/_cffi_backend.c:1890: error: ‘ffi_closure’ undeclared (first use in this function)
    c/_cffi_backend.c:1890: error: expected expression before ‘)’ token
    c/_cffi_backend.c: At top level:
    c/_cffi_backend.c:2503: error: expected declaration specifiers or ‘...’ before ‘ffi_abi’
    c/_cffi_backend.c: In function ‘cdata_call’:
    c/_cffi_backend.c:2632: error: ‘ffi_abi’ undeclared (first use in this function)
    c/_cffi_backend.c:2632: error: expected ‘;’ before ‘fabi’
    c/_cffi_backend.c:2674: error: ‘fabi’ undeclared (first use in this function)
    c/_cffi_backend.c:2678: error: too many arguments to function ‘fb_prepare_cif’
    c/_cffi_backend.c:2683: error: ‘cif_description_t’ has no member named ‘exchange_size’
    c/_cffi_backend.c:2693: error: ‘cif_description_t’ has no member named ‘exchange_offset_arg’
    c/_cffi_backend.c:2723: error: ‘cif_description_t’ has no member named ‘exchange_offset_arg’
    c/_cffi_backend.c:2728: warning: implicit declaration of function ‘ffi_call’
    c/_cffi_backend.c:2728: error: ‘cif_description_t’ has no member named ‘cif’
    c/_cffi_backend.c: In function ‘new_primitive_type’:
    c/_cffi_backend.c:3892: error: ‘ffi_type’ undeclared (first use in this function)
    c/_cffi_backend.c:3892: error: ‘ffitype’ undeclared (first use in this function)
    c/_cffi_backend.c:3910: error: ‘ffi_type_sint8’ undeclared (first use in this function)
    c/_cffi_backend.c:3911: error: ‘ffi_type_sint16’ undeclared (first use in this function)
    c/_cffi_backend.c:3912: error: ‘ffi_type_sint32’ undeclared (first use in this function)
    c/_cffi_backend.c:3913: error: ‘ffi_type_sint64’ undeclared (first use in this function)
    c/_cffi_backend.c:3919: error: ‘ffi_type_float’ undeclared (first use in this function)
    c/_cffi_backend.c:3921: error: ‘ffi_type_double’ undeclared (first use in this function)
    c/_cffi_backend.c:3929: error: ‘ffi_type_longdouble’ undeclared (first use in this function)
    c/_cffi_backend.c:3936: error: ‘ffi_type_uint8’ undeclared (first use in this function)
    c/_cffi_backend.c:3937: error: ‘ffi_type_uint16’ undeclared (first use in this function)
    c/_cffi_backend.c:3938: error: ‘ffi_type_uint32’ undeclared (first use in this function)
    c/_cffi_backend.c:3939: error: ‘ffi_type_uint64’ undeclared (first use in this function)
    c/_cffi_backend.c: At top level:
    c/_cffi_backend.c:4580: error: expected specifier-qualifier-list before ‘ffi_type’
    c/_cffi_backend.c:4599: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
    c/_cffi_backend.c: In function ‘fb_build’:
    c/_cffi_backend.c:4741: error: ‘struct funcbuilder_s’ has no member named ‘atypes’
    c/_cffi_backend.c:4741: error: ‘ffi_type’ undeclared (first use in this function)
    c/_cffi_backend.c:4741: error: expected expression before ‘)’ token
    c/_cffi_backend.c:4742: error: ‘struct funcbuilder_s’ has no member named ‘nargs’
    c/_cffi_backend.c:4745: error: ‘struct funcbuilder_s’ has no member named ‘rtype’
    c/_cffi_backend.c:4745: warning: implicit declaration of function ‘fb_fill_type’
    c/_cffi_backend.c:4753: error: ‘cif_description_t’ has no member named ‘exchange_offset_arg’
    c/_cffi_backend.c:4756: error: ‘struct funcbuilder_s’ has no member named ‘rtype’
    c/_cffi_backend.c:4757: error: ‘ffi_arg’ undeclared (first use in this function)
    c/_cffi_backend.c:4767: error: ‘atype’ undeclared (first use in this function)
    c/_cffi_backend.c:4780: error: ‘struct funcbuilder_s’ has no member named ‘atypes’
    c/_cffi_backend.c:4781: error: ‘struct funcbuilder_s’ has no member named ‘atypes’
    c/_cffi_backend.c:4784: error: ‘cif_description_t’ has no member named ‘exchange_offset_arg’
    c/_cffi_backend.c:4793: error: ‘cif_description_t’ has no member named ‘exchange_size’
    c/_cffi_backend.c: In function ‘fb_build_name’:
    c/_cffi_backend.c:4817: error: ‘struct funcbuilder_s’ has no member named ‘nargs’
    c/_cffi_backend.c:4829: error: ‘struct funcbuilder_s’ has no member named ‘fct’
    c/_cffi_backend.c:4832: error: ‘struct funcbuilder_s’ has no member named ‘fct’
    c/_cffi_backend.c: In function ‘fb_prepare_ctype’:
    c/_cffi_backend.c:4876: error: ‘struct funcbuilder_s’ has no member named ‘fct’
    c/_cffi_backend.c:4893: error: ‘struct funcbuilder_s’ has no member named ‘fct’
    c/_cffi_backend.c: At top level:
    c/_cffi_backend.c:4913: error: expected declaration specifiers or ‘...’ before ‘ffi_abi’
    c/_cffi_backend.c: In function ‘fb_prepare_cif’:
    c/_cffi_backend.c:4940: warning: implicit declaration of function ‘ffi_prep_cif’
    c/_cffi_backend.c:4940: error: ‘cif_description_t’ has no member named ‘cif’
    c/_cffi_backend.c:4940: error: ‘fabi’ undeclared (first use in this function)
    c/_cffi_backend.c:4940: error: ‘struct funcbuilder_s’ has no member named ‘nargs’
    c/_cffi_backend.c:4941: error: ‘struct funcbuilder_s’ has no member named ‘rtype’
    c/_cffi_backend.c:4941: error: ‘struct funcbuilder_s’ has no member named ‘atypes’
    c/_cffi_backend.c:4941: error: ‘FFI_OK’ undeclared (first use in this function)
    c/_cffi_backend.c: In function ‘new_function_type’:
    c/_cffi_backend.c:4985: error: too many arguments to function ‘fb_prepare_cif’
    c/_cffi_backend.c:4999: error: ‘struct funcbuilder_s’ has no member named ‘nargs’
    c/_cffi_backend.c:5009: error: ‘struct funcbuilder_s’ has no member named ‘nargs’
    c/_cffi_backend.c:5019: error: ‘struct funcbuilder_s’ has no member named ‘nargs’
    c/_cffi_backend.c:5022: error: ‘struct funcbuilder_s’ has no member named ‘nargs’
    c/_cffi_backend.c:5023: error: ‘struct funcbuilder_s’ has no member named ‘nargs’
    c/_cffi_backend.c:5025: error: ‘struct funcbuilder_s’ has no member named ‘nargs’
    c/_cffi_backend.c: In function ‘b_new_function_type’:
    c/_cffi_backend.c:5036: error: ‘FFI_DEFAULT_ABI’ undeclared (first use in this function)
    c/_cffi_backend.c: In function ‘convert_from_object_fficallback’:
    c/_cffi_backend.c:5056: error: ‘ffi_arg’ undeclared (first use in this function)
    c/_cffi_backend.c: At top level:
    c/_cffi_backend.c:5238: error: expected ‘)’ before ‘*’ token
    c/_cffi_backend.c: In function ‘prepare_callback_info_tuple’:
    c/_cffi_backend.c:5280: error: ‘ffi_arg’ undeclared (first use in this function)
    c/_cffi_backend.c: In function ‘b_callback’:
    c/_cffi_backend.c:5313: error: ‘ffi_closure’ undeclared (first use in this function)
    c/_cffi_backend.c:5313: error: ‘closure’ undeclared (first use in this function)
    c/_cffi_backend.c:5323: warning: implicit declaration of function ‘cffi_closure_alloc’
    c/_cffi_backend.c:5341: warning: implicit declaration of function ‘ffi_prep_closure’
    c/_cffi_backend.c:5341: error: ‘cif_description_t’ has no member named ‘cif’
    c/_cffi_backend.c:5342: error: ‘invoke_callback’ undeclared (first use in this function)
    c/_cffi_backend.c:5342: error: ‘FFI_OK’ undeclared (first use in this function)
    In file included from c/cffi1_module.c:3,
                     from c/_cffi_backend.c:6740:
    c/realize_c_type.c: In function ‘realize_c_type_or_func’:
    c/realize_c_type.c:577: error: ‘FFI_DEFAULT_ABI’ undeclared (first use in this function)
    c/_cffi_backend.c: In function ‘init_cffi_backend’:
    c/_cffi_backend.c:6832: error: ‘FFI_DEFAULT_ABI’ undeclared (first use in this function)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/var/tmp/pbs.175654.hpcc-con/pip-build-ITzT0C/pygit2/setup.py", line 210, in <module>
        **extra_args)
      File "/home/s1510756/py27/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/s1510756/py27/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/dist.py", line 315, in __init__
      File "/home/s1510756/py27/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/dist.py", line 361, in fetch_build_eggs
      File "/home/s1510756/py27/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 851, in resolve
      File "/home/s1510756/py27/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1123, in best_match
      File "/home/s1510756/py27/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1135, in obtain
      File "/home/s1510756/py27/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/dist.py", line 428, in fetch_build_egg
      File "/home/s1510756/py27/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/easy_install.py", line 664, in easy_install
      File "/home/s1510756/py27/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/easy_install.py", line 694, in install_item
      File "/home/s1510756/py27/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/easy_install.py", line 875, in install_eggs
      File "/home/s1510756/py27/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/easy_install.py", line 1114, in build_and_install
      File "/home/s1510756/py27/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/easy_install.py", line 1102, in run_setup
    distutils.errors.DistutilsError: Setup script exited with error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /var/tmp/pbs.175654.hpcc-con/pip-build-ITzT0C/pygit2/
Traceback (most recent call last):
  File "/home/s1510756/hpcc/vcc-combine.py", line 1, in <module>
    import matplotlib.pyplot as plt
ImportError: No module named matplotlib.pyplot
